#############################################################################
# Makefile for building: final
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  final.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile final.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_USE_MATH_DEFINES -DTIXML_USE_STL -DGLM_SWIZZLE -DGLM_FORCE_RADIANS -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++14 -g -g -std=gnu++1y -W -Waddress -Warray-bounds -Wc++0x-compat -Wchar-subscripts -Wformat -Wmain -Wmissing-braces -Wparentheses -Wreorder -Wreturn-type -Wsequence-point -Wsign-compare -Wstrict-overflow=1 -Wswitch -Wtrigraphs -Wuninitialized -Wunused-label -Wunused-variable -Wvolatile-register-var -Wno-extra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iglm -Iui -Iglew-1.10.0/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = final1.0.0
DISTDIR = /gpfs/main/home/mwu27/Desktop/final/.tmp/final1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lGLU -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ui/mainwindow.cpp \
		main.cpp \
		glew-1.10.0/src/glew.c \
		ui/view.cpp \
		ui/viewformat.cpp \
		uniforms/uniformvariable.cpp \
		camera/orbitingcamera.cpp \
		uniforms/varsfile.cpp \
		lib/resourceloader.cpp \
		shapes/openglshape.cpp \
		gl/datatype/FBO.cpp \
		gl/datatype/VBO.cpp \
		gl/datatype/VBOAttribMarker.cpp \
		gl/datatype/VAO.cpp \
		gl/datatype/IBO.cpp \
		gl/textures/Texture.cpp \
		gl/textures/Texture2D.cpp \
		gl/textures/TextureParameters.cpp \
		gl/textures/TextureParametersBuilder.cpp \
		gl/textures/RenderBuffer.cpp \
		gl/textures/DepthBuffer.cpp \
		gl/GLDebug.cpp \
		lib/errorchecker.cpp \
		gl/shaders/CS123Shader.cpp \
		gl/shaders/Shader.cpp \
		lib/RGBA.cpp \
		shapes/trees/SimpleTree.cpp \
		shapes/trees/StringGenerator.cpp \
		shapes/trees/StringParser.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_view.cpp \
		moc_orbitingcamera.cpp \
		moc_camera.cpp
OBJECTS       = mainwindow.o \
		main.o \
		glew.o \
		view.o \
		viewformat.o \
		uniformvariable.o \
		orbitingcamera.o \
		varsfile.o \
		resourceloader.o \
		openglshape.o \
		FBO.o \
		VBO.o \
		VBOAttribMarker.o \
		VAO.o \
		IBO.o \
		Texture.o \
		Texture2D.o \
		TextureParameters.o \
		TextureParametersBuilder.o \
		RenderBuffer.o \
		DepthBuffer.o \
		GLDebug.o \
		errorchecker.o \
		CS123Shader.o \
		Shader.o \
		RGBA.o \
		SimpleTree.o \
		StringGenerator.o \
		StringParser.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_view.o \
		moc_orbitingcamera.o \
		moc_camera.o
DIST          = shaders/normals/normals.vert \
		shaders/normals/normals.frag \
		shaders/normals/normals.gsh \
		shaders/normals/normalsArrow.gsh \
		shaders/normals/normalsArrow.frag \
		shaders/normals/normalsArrow.vert \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		final.pro ui/mainwindow.h \
		ui_mainwindow.h \
		glew-1.10.0/include/GL/glew.h \
		ui/view.h \
		ui/viewformat.h \
		uniforms/uniformvariable.h \
		lib/common.h \
		camera/orbitingcamera.h \
		camera/camera.h \
		uniforms/varsfile.h \
		shapes/cube.h \
		lib/resourceloader.h \
		shapes/sphere.h \
		shapes/openglshape.h \
		gl/datatype/FBO.h \
		gl/datatype/VBO.h \
		gl/datatype/VBOAttribMarker.h \
		gl/datatype/VAO.h \
		gl/datatype/IBO.h \
		gl/shaders/ShaderAttribLocations.h \
		gl/textures/Texture.h \
		gl/textures/Texture2D.h \
		gl/textures/TextureParameters.h \
		gl/textures/TextureParametersBuilder.h \
		gl/textures/RenderBuffer.h \
		gl/textures/DepthBuffer.h \
		gl/GLDebug.h \
		lib/errorchecker.h \
		gl/shaders/CS123Shader.h \
		gl/shaders/Shader.h \
		lib/CS123SceneData.h \
		lib/RGBA.h \
		shapes/trees/SimpleTree.h \
		shapes/trees/StringGenerator.h \
		shapes/trees/StringParser.h ui/mainwindow.cpp \
		main.cpp \
		glew-1.10.0/src/glew.c \
		ui/view.cpp \
		ui/viewformat.cpp \
		uniforms/uniformvariable.cpp \
		camera/orbitingcamera.cpp \
		uniforms/varsfile.cpp \
		lib/resourceloader.cpp \
		shapes/openglshape.cpp \
		gl/datatype/FBO.cpp \
		gl/datatype/VBO.cpp \
		gl/datatype/VBOAttribMarker.cpp \
		gl/datatype/VAO.cpp \
		gl/datatype/IBO.cpp \
		gl/textures/Texture.cpp \
		gl/textures/Texture2D.cpp \
		gl/textures/TextureParameters.cpp \
		gl/textures/TextureParametersBuilder.cpp \
		gl/textures/RenderBuffer.cpp \
		gl/textures/DepthBuffer.cpp \
		gl/GLDebug.cpp \
		lib/errorchecker.cpp \
		gl/shaders/CS123Shader.cpp \
		gl/shaders/Shader.cpp \
		lib/RGBA.cpp \
		shapes/trees/SimpleTree.cpp \
		shapes/trees/StringGenerator.cpp \
		shapes/trees/StringParser.cpp
QMAKE_TARGET  = final
DESTDIR       = 
TARGET        = final


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: final.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		final.pro \
		resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Xml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile final.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
final.pro:
resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Xml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile final.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.h ui_mainwindow.h glew-1.10.0/include/GL/glew.h ui/view.h ui/viewformat.h uniforms/uniformvariable.h lib/common.h camera/orbitingcamera.h camera/camera.h uniforms/varsfile.h shapes/cube.h lib/resourceloader.h shapes/sphere.h shapes/openglshape.h gl/datatype/FBO.h gl/datatype/VBO.h gl/datatype/VBOAttribMarker.h gl/datatype/VAO.h gl/datatype/IBO.h gl/shaders/ShaderAttribLocations.h gl/textures/Texture.h gl/textures/Texture2D.h gl/textures/TextureParameters.h gl/textures/TextureParametersBuilder.h gl/textures/RenderBuffer.h gl/textures/DepthBuffer.h gl/GLDebug.h lib/errorchecker.h gl/shaders/CS123Shader.h gl/shaders/Shader.h lib/CS123SceneData.h lib/RGBA.h shapes/trees/SimpleTree.h shapes/trees/StringGenerator.h shapes/trees/StringParser.h $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.cpp main.cpp glew-1.10.0/src/glew.c ui/view.cpp ui/viewformat.cpp uniforms/uniformvariable.cpp camera/orbitingcamera.cpp uniforms/varsfile.cpp lib/resourceloader.cpp shapes/openglshape.cpp gl/datatype/FBO.cpp gl/datatype/VBO.cpp gl/datatype/VBOAttribMarker.cpp gl/datatype/VAO.cpp gl/datatype/IBO.cpp gl/textures/Texture.cpp gl/textures/Texture2D.cpp gl/textures/TextureParameters.cpp gl/textures/TextureParametersBuilder.cpp gl/textures/RenderBuffer.cpp gl/textures/DepthBuffer.cpp gl/GLDebug.cpp lib/errorchecker.cpp gl/shaders/CS123Shader.cpp gl/shaders/Shader.cpp lib/RGBA.cpp shapes/trees/SimpleTree.cpp shapes/trees/StringGenerator.cpp shapes/trees/StringParser.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		ray.vert \
		normals.frag \
		shaders/shader.frag \
		skybox.vert \
		normals.gsh \
		normals.vert \
		ray.frag \
		shaders/shader.vert \
		skybox.frag \
		shaders/skybox/negx.jpg \
		shaders/skybox/posx.jpg \
		shaders/skybox/negz.jpg \
		shaders/skybox/posz.jpg \
		shaders/skybox/negy.jpg \
		shaders/skybox/posy.jpg
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++14 -g -g -std=gnu++1y -W -Waddress -Warray-bounds -Wc++0x-compat -Wchar-subscripts -Wformat -Wmain -Wmissing-braces -Wparentheses -Wreorder -Wreturn-type -Wsequence-point -Wsign-compare -Wstrict-overflow=1 -Wswitch -Wtrigraphs -Wuninitialized -Wunused-label -Wunused-variable -Wvolatile-register-var -Wno-extra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_view.cpp moc_orbitingcamera.cpp moc_camera.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_view.cpp moc_orbitingcamera.cpp moc_camera.cpp
moc_mainwindow.cpp: ui/mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /gpfs/main/home/mwu27/Desktop/final/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/gpfs/main/home/mwu27/Desktop/final -I/gpfs/main/home/mwu27/Desktop/final/glm -I/gpfs/main/home/mwu27/Desktop/final/ui -I/gpfs/main/home/mwu27/Desktop/final/glew-1.10.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ui/mainwindow.h -o moc_mainwindow.cpp

moc_view.cpp: shapes/openglshape.h \
		gl/datatype/VBO.h \
		glew-1.10.0/include/GL/glew.h \
		gl/datatype/VBOAttribMarker.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		camera/camera.h \
		uniforms/uniformvariable.h \
		lib/common.h \
		gl/datatype/FBO.h \
		gl/textures/TextureParameters.h \
		lib/CS123SceneData.h \
		gl/shaders/CS123Shader.h \
		gl/shaders/Shader.h \
		ui/view.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /gpfs/main/home/mwu27/Desktop/final/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/gpfs/main/home/mwu27/Desktop/final -I/gpfs/main/home/mwu27/Desktop/final/glm -I/gpfs/main/home/mwu27/Desktop/final/ui -I/gpfs/main/home/mwu27/Desktop/final/glew-1.10.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ui/view.h -o moc_view.cpp

moc_orbitingcamera.cpp: camera/camera.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		camera/orbitingcamera.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /gpfs/main/home/mwu27/Desktop/final/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/gpfs/main/home/mwu27/Desktop/final -I/gpfs/main/home/mwu27/Desktop/final/glm -I/gpfs/main/home/mwu27/Desktop/final/ui -I/gpfs/main/home/mwu27/Desktop/final/glew-1.10.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include camera/orbitingcamera.h -o moc_orbitingcamera.cpp

moc_camera.cpp: glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		camera/camera.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /gpfs/main/home/mwu27/Desktop/final/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/gpfs/main/home/mwu27/Desktop/final -I/gpfs/main/home/mwu27/Desktop/final/glm -I/gpfs/main/home/mwu27/Desktop/final/ui -I/gpfs/main/home/mwu27/Desktop/final/glew-1.10.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include camera/camera.h -o moc_camera.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ui/mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		ui/view.h \
		shapes/openglshape.h \
		gl/datatype/VBO.h \
		glew-1.10.0/include/GL/glew.h \
		gl/datatype/VBOAttribMarker.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		camera/camera.h \
		uniforms/uniformvariable.h \
		lib/common.h \
		gl/datatype/FBO.h \
		gl/textures/TextureParameters.h \
		lib/CS123SceneData.h \
		gl/shaders/CS123Shader.h \
		gl/shaders/Shader.h
	/usr/lib/qt5/bin/uic ui/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

mainwindow.o: ui/mainwindow.cpp ui/mainwindow.h \
		ui_mainwindow.h \
		ui/view.h \
		shapes/openglshape.h \
		gl/datatype/VBO.h \
		glew-1.10.0/include/GL/glew.h \
		gl/datatype/VBOAttribMarker.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		camera/camera.h \
		uniforms/uniformvariable.h \
		lib/common.h \
		gl/datatype/FBO.h \
		gl/textures/TextureParameters.h \
		lib/CS123SceneData.h \
		gl/shaders/CS123Shader.h \
		gl/shaders/Shader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ui/mainwindow.cpp

main.o: main.cpp ui/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

glew.o: glew-1.10.0/src/glew.c glew-1.10.0/include/GL/glew.h \
		glew-1.10.0/include/GL/wglew.h \
		glew-1.10.0/include/GL/glxew.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o glew.o glew-1.10.0/src/glew.c

view.o: ui/view.cpp ui/view.h \
		shapes/openglshape.h \
		gl/datatype/VBO.h \
		glew-1.10.0/include/GL/glew.h \
		gl/datatype/VBOAttribMarker.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		camera/camera.h \
		uniforms/uniformvariable.h \
		lib/common.h \
		gl/datatype/FBO.h \
		gl/textures/TextureParameters.h \
		lib/CS123SceneData.h \
		gl/shaders/CS123Shader.h \
		gl/shaders/Shader.h \
		ui/viewformat.h \
		shapes/sphere.h \
		shapes/cube.h \
		camera/orbitingcamera.h \
		lib/resourceloader.h \
		uniforms/varsfile.h \
		gl/shaders/ShaderAttribLocations.h \
		gl/textures/Texture2D.h \
		gl/textures/Texture.h \
		shapes/trees/SimpleTree.h \
		shapes/trees/StringParser.h \
		shapes/trees/StringGenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o ui/view.cpp

viewformat.o: ui/viewformat.cpp ui/viewformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewformat.o ui/viewformat.cpp

uniformvariable.o: uniforms/uniformvariable.cpp uniforms/uniformvariable.h \
		glew-1.10.0/include/GL/glew.h \
		lib/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uniformvariable.o uniforms/uniformvariable.cpp

orbitingcamera.o: camera/orbitingcamera.cpp camera/orbitingcamera.h \
		camera/camera.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		lib/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o orbitingcamera.o camera/orbitingcamera.cpp

varsfile.o: uniforms/varsfile.cpp uniforms/varsfile.h \
		uniforms/uniformvariable.h \
		glew-1.10.0/include/GL/glew.h \
		lib/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o varsfile.o uniforms/varsfile.cpp

resourceloader.o: lib/resourceloader.cpp lib/resourceloader.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resourceloader.o lib/resourceloader.cpp

openglshape.o: shapes/openglshape.cpp shapes/openglshape.h \
		gl/datatype/VBO.h \
		glew-1.10.0/include/GL/glew.h \
		gl/datatype/VBOAttribMarker.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		gl/datatype/VAO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openglshape.o shapes/openglshape.cpp

FBO.o: gl/datatype/FBO.cpp gl/datatype/FBO.h \
		gl/textures/TextureParameters.h \
		glew-1.10.0/include/GL/glew.h \
		gl/GLDebug.h \
		gl/textures/RenderBuffer.h \
		gl/textures/DepthBuffer.h \
		gl/textures/Texture2D.h \
		gl/textures/Texture.h \
		gl/textures/TextureParametersBuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FBO.o gl/datatype/FBO.cpp

VBO.o: gl/datatype/VBO.cpp gl/datatype/VBO.h \
		glew-1.10.0/include/GL/glew.h \
		gl/datatype/VBOAttribMarker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VBO.o gl/datatype/VBO.cpp

VBOAttribMarker.o: gl/datatype/VBOAttribMarker.cpp gl/datatype/VBOAttribMarker.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VBOAttribMarker.o gl/datatype/VBOAttribMarker.cpp

VAO.o: gl/datatype/VAO.cpp gl/datatype/VAO.h \
		glew-1.10.0/include/GL/glew.h \
		gl/datatype/VBO.h \
		gl/datatype/IBO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VAO.o gl/datatype/VAO.cpp

IBO.o: gl/datatype/IBO.cpp gl/datatype/IBO.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IBO.o gl/datatype/IBO.cpp

Texture.o: gl/textures/Texture.cpp gl/textures/Texture.h \
		glew-1.10.0/include/GL/glew.h \
		gl/GLDebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Texture.o gl/textures/Texture.cpp

Texture2D.o: gl/textures/Texture2D.cpp gl/textures/Texture2D.h \
		gl/textures/Texture.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Texture2D.o gl/textures/Texture2D.cpp

TextureParameters.o: gl/textures/TextureParameters.cpp gl/textures/TextureParameters.h \
		glew-1.10.0/include/GL/glew.h \
		gl/GLDebug.h \
		gl/textures/Texture.h \
		gl/textures/Texture2D.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextureParameters.o gl/textures/TextureParameters.cpp

TextureParametersBuilder.o: gl/textures/TextureParametersBuilder.cpp gl/textures/TextureParametersBuilder.h \
		gl/textures/TextureParameters.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextureParametersBuilder.o gl/textures/TextureParametersBuilder.cpp

RenderBuffer.o: gl/textures/RenderBuffer.cpp gl/textures/RenderBuffer.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RenderBuffer.o gl/textures/RenderBuffer.cpp

DepthBuffer.o: gl/textures/DepthBuffer.cpp gl/textures/DepthBuffer.h \
		gl/textures/RenderBuffer.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DepthBuffer.o gl/textures/DepthBuffer.cpp

GLDebug.o: gl/GLDebug.cpp gl/GLDebug.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLDebug.o gl/GLDebug.cpp

errorchecker.o: lib/errorchecker.cpp lib/errorchecker.h \
		glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errorchecker.o lib/errorchecker.cpp

CS123Shader.o: gl/shaders/CS123Shader.cpp gl/shaders/CS123Shader.h \
		gl/shaders/Shader.h \
		glew-1.10.0/include/GL/glew.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		lib/CS123SceneData.h \
		gl/GLDebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CS123Shader.o gl/shaders/CS123Shader.cpp

Shader.o: gl/shaders/Shader.cpp gl/shaders/Shader.h \
		glew-1.10.0/include/GL/glew.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		gl/GLDebug.h \
		gl/textures/Texture2D.h \
		gl/textures/Texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Shader.o gl/shaders/Shader.cpp

RGBA.o: lib/RGBA.cpp lib/RGBA.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RGBA.o lib/RGBA.cpp

SimpleTree.o: shapes/trees/SimpleTree.cpp shapes/trees/SimpleTree.h \
		glew-1.10.0/include/GL/glew.h \
		shapes/trees/StringParser.h \
		shapes/trees/StringGenerator.h \
		gl/shaders/ShaderAttribLocations.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		shapes/openglshape.h \
		gl/datatype/VBO.h \
		gl/datatype/VBOAttribMarker.h \
		glm/gtx/perpendicular.hpp \
		glm/gtx/projection.hpp \
		glm/gtx/projection.inl \
		glm/gtx/perpendicular.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SimpleTree.o shapes/trees/SimpleTree.cpp

StringGenerator.o: shapes/trees/StringGenerator.cpp shapes/trees/StringGenerator.h \
		gl/shaders/ShaderAttribLocations.h \
		glew-1.10.0/include/GL/glew.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		shapes/openglshape.h \
		gl/datatype/VBO.h \
		gl/datatype/VBOAttribMarker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StringGenerator.o shapes/trees/StringGenerator.cpp

StringParser.o: shapes/trees/StringParser.cpp shapes/trees/StringParser.h \
		shapes/trees/StringGenerator.h \
		gl/shaders/ShaderAttribLocations.h \
		glew-1.10.0/include/GL/glew.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/exponential.hpp \
		glm/detail/func_exponential.hpp \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/common.hpp \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/matrix.hpp \
		glm/detail/func_matrix.hpp \
		glm/detail/func_matrix.inl \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/gtx/transform.hpp \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtx/transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		shapes/openglshape.h \
		gl/datatype/VBO.h \
		gl/datatype/VBOAttribMarker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StringParser.o shapes/trees/StringParser.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

moc_orbitingcamera.o: moc_orbitingcamera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_orbitingcamera.o moc_orbitingcamera.cpp

moc_camera.o: moc_camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camera.o moc_camera.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

